version: '3.3'
services:
  api:
    container_name: 'api'
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - '8080:8080'
    volumes:
      - './:/go/src/app'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
   # environment:
   #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
   #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
