FROM golang:1.8

WORKDIR /go/src/app
COPY . .

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#RUN dep ensure

RUN go get github.com/pilu/fresh

#CMD [ "go", "run", "main.go" ]
CMD [ "fresh" ]
